### PR TITLE
Add support for creating subscriptions with filters.

### PR DESCRIPTION
**Pull request by enginoid**
In Cloud Pub/Sub, you can specify a filter in order to only receive messages matching that filter on a subscription. This change adds the ability to add a filter when creating a subscription.

This change also updates `Subscription.create(...)` to return the server's response rather than the subscription that's passed into the function. As I was making this change, I noticed that the test didn't respond to incorrect values returned by the bypass response in the test – ie. the bypass response could have returned anything and it wouldn't have failed the test. That's because the behavior of `Subscription.create(...)` was to return back directly the `Kane.Subscription` that was passed in rather than the one decoded from the response body.

In order to write a test that verifies that we correctly read the filter back from the server response, I needed to change this behavior to use the response body instead of just echoing back the subscription. This required a bit of code around stripping away the prefixes of the subscription and topic, which I suspect was the reason that the code wasn't reading back the response from the server.

### CODE REVIEW

**Review by joladev — APPROVED** [review]
awesome

**Comment by enginoid** [comment]
Oh, testing wise...

I did set up an integration test file that uses a local docker container. This is working great, except I kept getting 400 errors from the emulator when I added the filter parameter to the request. After a bit of digging, it looks like the emulator doesn't support filtering, and although it isn't explicit in the docs, that seems to extend to using the filter parameter when creating subscriptions. So unfortunately I'll have to verify this change with a real underlying pub/sub thing before I merge it in.

**Comment by joladev** [comment]
> it looks like the emulator doesn't support filtering

that's a bit annoying for running this in clustered mode locally

**Comment by enginoid** [comment]
I've been able to verify this works with the real Pub/Sub service:

## Code

```elixir
defmodule PubSubTest do
  alias Kane.Topic
  alias Kane.Subscription

  def main do
    sub = %Subscription{
      name: "freds-test-subscription-with-filter",
      topic: %Topic{name: "freds-test-topic"},
      filter: "attributes:domain"
    }

    IO.inspect(Subscription.create(sub))
  end
end

PubSubTest.main()
```

## Output

```elixir
{:ok,
 %Kane.Subscription{
   ack_deadline: 10,
   filter: "attributes:domain",
   name: "freds-test-subscription-with-filter",
   topic: %Kane.Topic{name: "freds-test-topic"}
 }}
```

## Screenshot
Screenshot 2021-08-05 at 16 44 45

**Comment by enginoid** [comment]
Proposed upstream: https://github.com/peburrows/kane/pull/36

**Pull request merged**
